#!/usr/bin/env bash

jmeter -n -t tests/non-functional/performance/performance_testing_module_A.jmx

cd tests/non-functional/performance/results/

find . -type d -mindepth 1 -exec sh -c '
name=$(basename "{}")
rm -r "$name"/html/
jmeter -g "$name"/"$name"-results.csv -o "$name"/html/
' \;
